apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  default.conf: |
    upstream backend {
      server localhost:3000;
    }

    # inactive means we keep stuff around for 1440m minutes regardless of last access (1 week)
    # levels means it is a 2 deep hierarchy cause we can have lots of files
    # max_size limits the size of the cache
    proxy_cache_path /tmp/nginx_cache inactive=1440m levels=1:2 keys_zone=one:10m max_size=500m;

    server {
      access_log /var/log/nginx/access.log;

      listen 80;

      # gzip
      gzip on;
      gzip_vary on;
      gzip_min_length 1000;
      gzip_comp_level 5;
      gzip_types application/javascript image/svg+xml text/css;
      gzip_proxied any;

      server_tokens off;

      client_max_body_size 10m;

      proxy_set_header Host $http_host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto https;


      location ~ ^/assets/.*$ {
        proxy_cache one;
        proxy_cache_key "$request_uri";
        proxy_ignore_headers Cache-Control Expires;
        expires 1y;
        proxy_cache_valid 200 301 302 1y;
        proxy_pass http://backend;
      }

      location / {
        proxy_pass http://backend;
      }

      location ~ ^/(admin_sign_in|admin|system) {
        auth_basic "Ce site vous demande de vous connecter";
        auth_basic_user_file /etc/nginx-secret/htpasswd;
      }
    }
