apiVersion: apps/v1
kind: Deployment
metadata:
  name: decidim-an-deployment
spec:
  selector:
    matchLabels:
      app: decidim-an-app
  template:
    metadata:
      labels:
        app: decidim-an-app
    spec:
      tolerations:
      - key: "k8s.scaleway.com/dedicated"
        value: "decidim-app"
        effect: "NoSchedule"
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - decidim-an-app
                topologyKey: topology.kubernetes.io/zone
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf
        - name: htpasswd
          secret:
            secretName: htpasswd
      containers:
      - image: nginx:alpine
        imagePullPolicy: Always
        name: web
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        env:
        - name: BACKEND_HOST
          value: localhost
        resources: 
          requests:
            cpu: "100m"
            memory: "80Mi"
          limits:
            memory: "400Mi"
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d
        - name: htpasswd
          mountPath: "/etc/nginx-secret/"
          readOnly: true
        startupProbe:
          httpGet:
            path: /health_check
            port: 80
          initialDelaySeconds: 10
          failureThreshold: 3
          periodSeconds: 10
      - name: app
        image: rg.fr-par.scw.cloud/decidim-an/decidim-an:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "500m"
            memory: "450Mi"
          limits:
            cpu: "2"
            memory: "1200Mi"
        env:
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        envFrom:
          - configMapRef:
              name: decidim-an-app-config
          - secretRef:
              name: decidim-an-app-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: decidim-an-svc
spec:
  selector:
    app: decidim-an-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: decidim-an-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: decidim-an-deployment
  minReplicas: 10
  maxReplicas: 40
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 20
