apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: decidim-an-ingress
spec:
  rules:
  - host: petitions.assemblee-nationale.fr
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: decidim-an-svc
            port:
              number: 80
